# Generated by Django 4.2.3 on 2023-07-31 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recipe_name", models.CharField(max_length=50)),
                ("recipe_des", models.TextField(max_length=500)),
                ("recipe_img", models.ImageField(upload_to="recipe")),
            ],
        ),
    ]
